<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.muenchendigital.digiwf</groupId>
        <artifactId>digiwf-core</artifactId>
        <version>0.17.1-SNAPSHOT</version>
    </parent>


    <artifactId>digiwf-task</artifactId>
    <name>${project.artifactId}</name>
    <packaging>pom</packaging>
    <description>Task management used by DigiWF</description>

    <properties>
        <polyflow.version>3.7.0</polyflow.version>
        <axon-framework.version>4.6.3</axon-framework.version>
        <axon-extension-kafka.version>4.6.0</axon-extension-kafka.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring.boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>io.holunda.polyflow</groupId>
                <artifactId>polyflow-taskpool-dependencies</artifactId>
                <version>${polyflow.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <modules>
        <module>digiwf-tasklist-service</module>
        <module>digiwf-polyflow-connector</module>
    </modules>

</project>
