version: 2

updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "Technical Dept"
    # Disable version updates for github-actions dependencies
    open-pull-requests-limit: 0

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "Technical Dept"
    # Disable version updates for maven dependencies
    open-pull-requests-limit: 0

  - package-ecosystem: npm
    directory: "/docs"
    target-branch: "dev"
    labels:
      - "Technical Dept"
    schedule:
      interval: weekly
    # Disable version updates for npm dependencies (docs)
    open-pull-requests-limit: 0
