export interface Labels {
  title: string,
  description: string,
  key: string,
  ui: string,
  general: string,
  section: string,
  optionalObject: string,
  optionalSelectItem: string,
  optionalGroup: string,
  optionalFields: string,
  markdown: string,
  list: string,
  switch: string;
  dmsInput: string;
  multiUserInput: string;
  userInput: string;
  files: string;
  select: string;
  multiSelect: string;
  time: string;
  date: string;
  checkbox: string;
  floatNumber: string;
  number: string;
  textarea: string;
  text: string;
  options: string;
  dynamicObject: string;
  dynamicObjectList: string;
  containerDescription: string;
  maxColSize: string;
  defaultColSize: string;
  colSizeSmallDevices: string;
  default: string;
  messages: string;
  validation: string;
  type: string;
  errorMsgPattern: string;
  errorMsgMinString: string;
  errorMsgMaxString: string;
  errorMsgMinNumber: string;
  errorMsgMaxNumber: string;
  errorMsgMinArray: string;
  errorMsgMaxArray: string;
  validationMin: string;
  validationMax: string;
  validationAdditionalRules: string;
  dmsSystem: string;
  dmsObjectClass: string;
  dmsSchriftstueck: string;
  dmsSachakte: string;
  dmsVorgang: string;
  dmsEingang: string;
  dmsAusgang: string;
  dmsIntern: string;
  dmsDefaultDescription: string;
}
