logging.level.io.muenchendigital=info
logging.level.org.springframework=info
spring.cloud.stream.kafka.binder.brokers=localhost:9092
io.muenchendigital.digiwf.cosys.engineTopic=dwf-digiwf-engine-local-01
io.muenchendigital.digiwf.cosys.topic=dwf-cosys-local-01
digiwf.streaming.group="dwf-cosys-service"
# cosys
io.muenchendigital.digiwf.cosys.url=http://cosysk007.srv.muenchen.de/cosys-eai/rest
io.muenchendigital.digiwf.cosys.merge.datafile=//multi
io.muenchendigital.digiwf.cosys.merge.inputLanguage=Deutsch
io.muenchendigital.digiwf.cosys.merge.outputLanguage=Deutsch
io.muenchendigital.digiwf.cosys.merge.keepFields=unresolved-ref
io.muenchendigital.digiwf.cosys.ssoTokenClientSecret=e2b2b018-abe5-4057-81b9-afdeeab4d8de
io.muenchendigital.digiwf.cosys.ssoTokenRequestUrl=https://ssotest.muenchen.de/auth/realms/intra/protocol/openid-connect/token
io.muenchendigital.digiwf.cosys.ssoTokenClientID=digitalwf

spring.security.oauth2.client.registration.cosys.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.cosys.client-id=digitalwf
spring.security.oauth2.client.registration.cosys.client-secret=e2b2b018-abe5-4057-81b9-afdeeab4d8de
spring.security.oauth2.client.provider.cosys.token-uri=https://ssotest.muenchen.de/auth/realms/intra/protocol/openid-connect/token