server.port=8086
spring.application.name=example app
spring.banner.location=banner.txt
# env may be local,dev,test,demo,processesdemo, ...
digiwf.env=local
# streaming topics
digiwf.streaming.engine.topics=dwf-digiwf-engine-${digiwf.env}
digiwf.streaming.s3.topics=dwf-s3-${digiwf.env}
digiwf.streaming.group="dwf-s3-service"
