server.port=8080
# env may be local,dev,test,demo,processesdemo, ...
digiwf.env=local
# streaming topics
digiwf.streaming.engine.topics=dwf-digiwf-engine-${digiwf.env}
digiwf.streaming.email.topics=dwf-email-${digiwf.env}
digiwf.streaming.group="dwf-email-service"
