#spring cloud stream
spring.cloud.stream.function.routing.enabled=true
spring.cloud.function.definition=sendCorrelateMessage;functionRouter;
spring.cloud.stream.bindings.functionRouter-in-0.destination=${digiwf.streaming.s3.topics}
spring.cloud.stream.bindings.functionRouter-in-0.group=${digiwf.streaming.group}
spring.cloud.stream.bindings.sendCorrelateMessage-out-0.destination=${digiwf.streaming.engine.topics}
#kafka config
spring.cloud.stream.kafka.binder.consumerProperties.key.deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.cloud.stream.kafka.binder.consumerProperties.value.deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.cloud.stream.kafka.binder.producerProperties.key.serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.cloud.stream.kafka.binder.producerProperties.value.serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.cloud.stream.kafka.binder.consumerProperties.auto.offset.reset=latest
#spring.cloud.stream.kafka.binder.configuration.security.protocol=SSL
spring.cloud.stream.bindings.sendMessage-out-0.destination=${digiwf.streaming.engine.topics}
io.muenchendigital.digiwf.streaming.typeMappings.createPresignedUrl=createPresignedUrl
