#
# Use this only in dev environments. It's not intended for production usage.
#
# Profiles:
# - tasklist: starts an nginx on 8081 and tasklist behind it.
#
#

version: '3.5'

networks:
  local-keycloak:

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '22181:2181'

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - '29092:29092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  init-kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka:9092 --list
      
      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic dfw-taskmanagement-tasks-local-01 --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic dfw-taskmanagement-data-local-01 --replication-factor 1 --partitions 1
      
      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:9092 --list
      "     

  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: Test1234
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./minio:/data

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - '1025:1025' # smtp server
      - '9025:8025' # ui

  digiwf-gateway:
    image: itatm/digiwf-gateway:dev
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: local,local-docker,no-security
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  postgres-tasklist:
    image: postgres:13.2
    container_name: digiwf-postgres-tasklist
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: tasklistdb
    ports:
      - '25432:5432'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  postgres-engine:
    image: postgres:13.2
    container_name: digiwf-postgres-engine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: enginedb
    ports:
      - '25433:5432'
    extra_hosts:
      - 'host.docker.internal:host-gateway'


  postgres-keycloak:
    image: postgres:13.2
    container_name: digiwf-postgres-keycloak
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_NAME:-keycloak}
      POSTGRES_USER: ${KEYCLOAK_DB_USER:-keycloak-user}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD:-keycloak-secret}
    networks:
      - local-keycloak

  keycloak: # https://hub.docker.com/r/jboss/keycloak
    container_name: digiwf-keycloak
    image: ${KEYCLOAK_IMAGE:-jboss/keycloak:16.1.1}
    depends_on:
      - postgres-keycloak
    networks:
      - local-keycloak
    ports:
      - '18080:8080'
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres-keycloak
      DB_DATABASE: ${KEYCLOAK_DB_NAME:-keycloak}
      DB_USER: ${KEYCLOAK_DB_USER:-keycloak-user}
      DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD:-keycloak-secret}
      KEYCLOAK_USER: ${KEYCLOAK_USER:-admin}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD:-admin}

  init-keycloak:
    image: klg71/keycloakmigration
    depends_on:
      - keycloak
    env_file:
      - './local.env'
    environment:
      ADMIN_USER: ${KEYCLOAK_USER:-admin}
      ADMIN_PASSWORD: ${KEYCLOAK_USER:-admin}
      BASEURL:  http://keycloak:8080/auth # uses internal docker network to access the keycloak via its back channel port
      WAIT_FOR_KEYCLOAK: 'true'
      KEYCLOAK_CHANGELOG: /migration/keycloak-changelog.yml
      KEYCLOAK_REALM: ${SSO_REALM:-localrealm}
      TASK_CLIENT_ID: ${SSO_TASK_CLIENT_ID:-task-management}
      ENGINE_CLIENT_ID: ${SSO_ENGINE_CLIENT_ID:-digitalwf}
    volumes:
      - './keycloak:/migration'
    networks:
      - local-keycloak


  # enable the tasklist with --profile tasklist if you don't want to run it locally -> access it via http://localhost:8081/ then.
  #
  nginx:
    image: nginx:1.23.3
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8081:8080'
    depends_on:
      - digiwf-gateway
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    profiles:
      - tasklist
  digiwf-tasklist:
    image: itatm/digiwf-tasklist:dev
    ports:
      - '8091:8080'
    profiles:
      - tasklist

