info.application.name=DigiWF Engine
info.application.version=0.1.0
#Camunda
camunda.bpm.authorization.enabled=false
camunda.bpm.job-executor-acquire-by-priority=true
camunda.bpm.generic-properties.properties.history-time-to-live=185
camunda.bpm.generic-properties.properties.history-cleanup-strategy=removalTimeBased
camunda.bpm.generic-properties.properties.history-cleanup-batch-window-start-time=22:00
camunda.bpm.generic-properties.properties.history-cleanup-batch-window-end-time=06:00
camunda.bpm.generic-properties.properties.history-removal-time-strategy=end
camunda.bpm.generic-properties.properties.history-cleanup-degree-of-parallelism=4
#DigiWF Properties
digiwf.streaming=null
digiwf.base.frontendUrl=http://localhost:8081
digiwf.mail.defaultFromAddress=itm.digiwf@muenchen.de
digiwf.mail.defaultReceiverAddress=itm.digiwf-test@muenchen.de
digiwf.mail.overrideReceivers=true
digiwf.cosys.address=http://localhost:8091/
digiwf.alw.personeninfo.eaiUrl=http://localhost:9010/
digiwf.alw.dms.eaiUrl=http://localhost:9010/
digiwf.alw.dms.uiurl=https://alwdmstest02.muenchen.de/fsc/mx/%s
digiwf.parkausweis.url=http://localhost:9011/
digiwf.dms.address=http://localhost:8181/services/dms
digiwf.dms.username=eaiclient
digiwf.dms.uiurl=https://dmstest04.muenchen.de/fsc/mx/%s
digiwf.form.autodeploy=true
digiwf.form.autodeployBausteine=true
digiwf.form.whitelist=^[\w\s\?\!\#\=\.§\%\/\(\);:,@€\-\'\u00C0-\u017F]*$
digiwf.config.autodeploy=true
digiwf.jsonschema.autodeploy=true
digiwf.cleanup.expired-process-instances=0 0 23 * * ?
digiwf.s3service.topic=dwf-s3-local-01
digiwf.s3service.httpAPI=http://localhost:8086
directory.ldap.contextSource=ldaps://ldaptngtest.muenchen.de:636
directory.ldap.personSearchBase=o=lhm,c=de
directory.ldap.personObjectClasses=person,lhmPerson
directory.ldap.ouSearchBase=o=Landeshauptstadt München,c=de
directory.ldap.ouObjectClasses=lhmOrganizationalUnit

io.muenchendigital.digiwf.s3.client.document-storage-url=${digiwf.s3service.httpAPI}
#Actuator
management.server.port=${server.port}
management.endpoints.enabled-by-default=false
management.endpoints.web.exposure.include=health, info, prometheus
management.endpoints.web.path-mapping.prometheus=metrics
management.endpoint.health.enabled=true
management.endpoint.info.enabled=true
management.endpoint.prometheus.enabled=true
management.health.ldap.enabled=false
#Security
realm=P82
keycloak.auth-server-url=https://ssodev.muenchen.de/auth
security.logging.requests=all
security.oauth2.resource.jwk.key-set-uri=https://ssodev.muenchen.de/auth/realms/${realm}/protocol/openid-connect/certs
security.oauth2.resource.user-info-uri=https://ssodev.muenchen.de/auth/realms/${realm}/protocol/openid-connect/userinfo
security.oauth2.resource.prefer-token-info=false
security.oauth2.client.client-id=digitalwf
security.oauth2.client.client-secret=null
#Spring
server.port=39146
server.error.include-exception=false
server.error.include-stacktrace=never
server.error.whitelabel.enabled=false
spring.application.name=DigiWF Engine
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:~/backenddb;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database=H2
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=false
#Mail
spring.mail.host=mail.muenchen.de
spring.mail.port=587
spring.mail.username=itm.digiwf
spring.mail.properties.mail.debug=false
spring.mail.properties.mail.tls=true
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.host=mail.muenchen.de
spring.mail.properties.mail.smtp.port=587
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.trust=*
spring.mail.properties.mail.smtp.ssl.checkserveridentity=false
spring.mail.properties.mail.smtp.socketFactory.fallback=true
spring.mail.properties.mail.smtp.starttls.enable=true
#OpenAPI
springdoc.packagesToScan=de.muenchen.digitalwf
springdoc.pathsToMatch=/**
springdoc.swagger-ui.oauth.clientId=DigiWF
springdoc.swagger-ui.oauth.clientSecret=null
springdoc.swagger-ui.oauth.realm=Test
springdoc.swagger-ui.oauth.appName=DigiWF
springdoc.swagger-ui.csrf.enabled=false
springdoc.writer-with-default-pretty-printer=true
