/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AlwMetaDataTO
 */
export interface AlwMetaDataTO {
    /**
     * 
     * @type {string}
     * @memberof AlwMetaDataTO
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AlwMetaDataTO
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof AlwMetaDataTO
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof AlwMetaDataTO
     */
    extension?: string;
    /**
     * 
     * @type {string}
     * @memberof AlwMetaDataTO
     */
    contentSize?: string;
}

/**
 * Check if a given object implements the AlwMetaDataTO interface.
 */
export function instanceOfAlwMetaDataTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function AlwMetaDataTOFromJSON(json: any): AlwMetaDataTO {
    return AlwMetaDataTOFromJSONTyped(json, false);
}

export function AlwMetaDataTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlwMetaDataTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'extension': !exists(json, 'extension') ? undefined : json['extension'],
        'contentSize': !exists(json, 'contentSize') ? undefined : json['contentSize'],
    };
}

export function AlwMetaDataTOToJSON(value?: AlwMetaDataTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'type': value.type,
        'url': value.url,
        'extension': value.extension,
        'contentSize': value.contentSize,
    };
}

