/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ButtonTO } from './ButtonTO';
import {
    ButtonTOFromJSON,
    ButtonTOFromJSONTyped,
    ButtonTOToJSON,
} from './ButtonTO';

/**
 * 
 * @export
 * @interface ButtonsTO
 */
export interface ButtonsTO {
    /**
     * 
     * @type {ButtonTO}
     * @memberof ButtonsTO
     */
    complete?: ButtonTO;
    /**
     * 
     * @type {ButtonTO}
     * @memberof ButtonsTO
     */
    cancel?: ButtonTO;
    /**
     * 
     * @type {ButtonTO}
     * @memberof ButtonsTO
     */
    statusPdf?: ButtonTO;
}

/**
 * Check if a given object implements the ButtonsTO interface.
 */
export function instanceOfButtonsTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ButtonsTOFromJSON(json: any): ButtonsTO {
    return ButtonsTOFromJSONTyped(json, false);
}

export function ButtonsTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ButtonsTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'complete': !exists(json, 'complete') ? undefined : ButtonTOFromJSON(json['complete']),
        'cancel': !exists(json, 'cancel') ? undefined : ButtonTOFromJSON(json['cancel']),
        'statusPdf': !exists(json, 'statusPdf') ? undefined : ButtonTOFromJSON(json['statusPdf']),
    };
}

export function ButtonsTOToJSON(value?: ButtonsTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'complete': ButtonTOToJSON(value.complete),
        'cancel': ButtonTOToJSON(value.cancel),
        'statusPdf': ButtonTOToJSON(value.statusPdf),
    };
}

