/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ButtonTO
 */
export interface ButtonTO {
    /**
     * 
     * @type {boolean}
     * @memberof ButtonTO
     */
    showButton?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ButtonTO
     */
    buttonText?: string;
}

/**
 * Check if a given object implements the ButtonTO interface.
 */
export function instanceOfButtonTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ButtonTOFromJSON(json: any): ButtonTO {
    return ButtonTOFromJSONTyped(json, false);
}

export function ButtonTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ButtonTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'showButton': !exists(json, 'showButton') ? undefined : json['showButton'],
        'buttonText': !exists(json, 'buttonText') ? undefined : json['buttonText'],
    };
}

export function ButtonTOToJSON(value?: ButtonTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'showButton': value.showButton,
        'buttonText': value.buttonText,
    };
}

