/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompleteTO
 */
export interface CompleteTO {
    /**
     * 
     * @type {string}
     * @memberof CompleteTO
     */
    taskId: string;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof CompleteTO
     */
    variables: { [key: string]: object; };
}

/**
 * Check if a given object implements the CompleteTO interface.
 */
export function instanceOfCompleteTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "taskId" in value;
    isInstance = isInstance && "variables" in value;

    return isInstance;
}

export function CompleteTOFromJSON(json: any): CompleteTO {
    return CompleteTOFromJSONTyped(json, false);
}

export function CompleteTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompleteTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'taskId': json['taskId'],
        'variables': json['variables'],
    };
}

export function CompleteTOToJSON(value?: CompleteTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'taskId': value.taskId,
        'variables': value.variables,
    };
}

