/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigEntryTO
 */
export interface ConfigEntryTO {
    /**
     * 
     * @type {string}
     * @memberof ConfigEntryTO
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigEntryTO
     */
    value: string;
}

/**
 * Check if a given object implements the ConfigEntryTO interface.
 */
export function instanceOfConfigEntryTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "key" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function ConfigEntryTOFromJSON(json: any): ConfigEntryTO {
    return ConfigEntryTOFromJSONTyped(json, false);
}

export function ConfigEntryTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigEntryTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': json['key'],
        'value': json['value'],
    };
}

export function ConfigEntryTOToJSON(value?: ConfigEntryTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'value': value.value,
    };
}

