/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeploymentStatusDto
 */
export interface DeploymentStatusDto {
    /**
     * 
     * @type {boolean}
     * @memberof DeploymentStatusDto
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DeploymentStatusDto
     */
    message?: string;
}

/**
 * Check if a given object implements the DeploymentStatusDto interface.
 */
export function instanceOfDeploymentStatusDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DeploymentStatusDtoFromJSON(json: any): DeploymentStatusDto {
    return DeploymentStatusDtoFromJSONTyped(json, false);
}

export function DeploymentStatusDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeploymentStatusDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function DeploymentStatusDtoToJSON(value?: DeploymentStatusDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'message': value.message,
    };
}

