/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeploymentDto
 */
export interface DeploymentDto {
    /**
     * 
     * @type {string}
     * @memberof DeploymentDto
     */
    deploymentId?: string;
    /**
     * 
     * @type {string}
     * @memberof DeploymentDto
     */
    versionId?: string;
    /**
     * 
     * @type {string}
     * @memberof DeploymentDto
     */
    target?: string;
    /**
     * 
     * @type {string}
     * @memberof DeploymentDto
     */
    file?: string;
    /**
     * 
     * @type {string}
     * @memberof DeploymentDto
     */
    artifactType?: string;
}

/**
 * Check if a given object implements the DeploymentDto interface.
 */
export function instanceOfDeploymentDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DeploymentDtoFromJSON(json: any): DeploymentDto {
    return DeploymentDtoFromJSONTyped(json, false);
}

export function DeploymentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeploymentDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'deploymentId': !exists(json, 'deploymentId') ? undefined : json['deploymentId'],
        'versionId': !exists(json, 'versionId') ? undefined : json['versionId'],
        'target': !exists(json, 'target') ? undefined : json['target'],
        'file': !exists(json, 'file') ? undefined : json['file'],
        'artifactType': !exists(json, 'artifactType') ? undefined : json['artifactType'],
    };
}

export function DeploymentDtoToJSON(value?: DeploymentDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'deploymentId': value.deploymentId,
        'versionId': value.versionId,
        'target': value.target,
        'file': value.file,
        'artifactType': value.artifactType,
    };
}

