/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FollowUpTO
 */
export interface FollowUpTO {
    /**
     * 
     * @type {string}
     * @memberof FollowUpTO
     */
    taskId: string;
    /**
     * 
     * @type {string}
     * @memberof FollowUpTO
     */
    followUpDate?: string;
}

/**
 * Check if a given object implements the FollowUpTO interface.
 */
export function instanceOfFollowUpTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "taskId" in value;

    return isInstance;
}

export function FollowUpTOFromJSON(json: any): FollowUpTO {
    return FollowUpTOFromJSONTyped(json, false);
}

export function FollowUpTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FollowUpTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'taskId': json['taskId'],
        'followUpDate': !exists(json, 'followUpDate') ? undefined : json['followUpDate'],
    };
}

export function FollowUpTOToJSON(value?: FollowUpTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'taskId': value.taskId,
        'followUpDate': value.followUpDate,
    };
}

