/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ItemTO } from './ItemTO';
import {
    ItemTOFromJSON,
    ItemTOFromJSONTyped,
    ItemTOToJSON,
} from './ItemTO';
import type { RuleTO } from './RuleTO';
import {
    RuleTOFromJSON,
    RuleTOFromJSONTyped,
    RuleTOToJSON,
} from './RuleTO';

/**
 * 
 * @export
 * @interface FormFieldTO
 */
export interface FormFieldTO {
    /**
     * 
     * @type {string}
     * @memberof FormFieldTO
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof FormFieldTO
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof FormFieldTO
     */
    defaultValue?: string;
    /**
     * 
     * @type {string}
     * @memberof FormFieldTO
     */
    defaultValueField?: string;
    /**
     * 
     * @type {string}
     * @memberof FormFieldTO
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof FormFieldTO
     */
    prependIcon?: string;
    /**
     * 
     * @type {string}
     * @memberof FormFieldTO
     */
    tooltip?: string;
    /**
     * 
     * @type {string}
     * @memberof FormFieldTO
     */
    ext?: string;
    /**
     * 
     * @type {boolean}
     * @memberof FormFieldTO
     */
    multiple?: boolean;
    /**
     * 
     * @type {string}
     * @memberof FormFieldTO
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof FormFieldTO
     */
    ldapOus?: string;
    /**
     * 
     * @type {string}
     * @memberof FormFieldTO
     */
    imageHeight?: string;
    /**
     * 
     * @type {string}
     * @memberof FormFieldTO
     */
    imageWidth?: string;
    /**
     * 
     * @type {boolean}
     * @memberof FormFieldTO
     */
    readonly?: boolean;
    /**
     * 
     * @type {number}
     * @memberof FormFieldTO
     */
    rows?: number;
    /**
     * 
     * @type {number}
     * @memberof FormFieldTO
     */
    col?: number;
    /**
     * 
     * @type {Array<ItemTO>}
     * @memberof FormFieldTO
     */
    items?: Array<ItemTO>;
    /**
     * 
     * @type {Array<RuleTO>}
     * @memberof FormFieldTO
     */
    rules?: Array<RuleTO>;
    /**
     * 
     * @type {string}
     * @memberof FormFieldTO
     */
    itemText?: string;
    /**
     * 
     * @type {string}
     * @memberof FormFieldTO
     */
    itemValue?: string;
    /**
     * 
     * @type {boolean}
     * @memberof FormFieldTO
     */
    returnObject?: boolean;
}

/**
 * Check if a given object implements the FormFieldTO interface.
 */
export function instanceOfFormFieldTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "key" in value;

    return isInstance;
}

export function FormFieldTOFromJSON(json: any): FormFieldTO {
    return FormFieldTOFromJSONTyped(json, false);
}

export function FormFieldTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FormFieldTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'key': json['key'],
        'defaultValue': !exists(json, 'defaultValue') ? undefined : json['defaultValue'],
        'defaultValueField': !exists(json, 'defaultValueField') ? undefined : json['defaultValueField'],
        'label': !exists(json, 'label') ? undefined : json['label'],
        'prependIcon': !exists(json, 'prependIcon') ? undefined : json['prependIcon'],
        'tooltip': !exists(json, 'tooltip') ? undefined : json['tooltip'],
        'ext': !exists(json, 'ext') ? undefined : json['ext'],
        'multiple': !exists(json, 'multiple') ? undefined : json['multiple'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'ldapOus': !exists(json, 'ldapOus') ? undefined : json['ldapOus'],
        'imageHeight': !exists(json, 'imageHeight') ? undefined : json['imageHeight'],
        'imageWidth': !exists(json, 'imageWidth') ? undefined : json['imageWidth'],
        'readonly': !exists(json, 'readonly') ? undefined : json['readonly'],
        'rows': !exists(json, 'rows') ? undefined : json['rows'],
        'col': !exists(json, 'col') ? undefined : json['col'],
        'items': !exists(json, 'items') ? undefined : ((json['items'] as Array<any>).map(ItemTOFromJSON)),
        'rules': !exists(json, 'rules') ? undefined : ((json['rules'] as Array<any>).map(RuleTOFromJSON)),
        'itemText': !exists(json, 'itemText') ? undefined : json['itemText'],
        'itemValue': !exists(json, 'itemValue') ? undefined : json['itemValue'],
        'returnObject': !exists(json, 'returnObject') ? undefined : json['returnObject'],
    };
}

export function FormFieldTOToJSON(value?: FormFieldTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'key': value.key,
        'defaultValue': value.defaultValue,
        'defaultValueField': value.defaultValueField,
        'label': value.label,
        'prependIcon': value.prependIcon,
        'tooltip': value.tooltip,
        'ext': value.ext,
        'multiple': value.multiple,
        'description': value.description,
        'ldapOus': value.ldapOus,
        'imageHeight': value.imageHeight,
        'imageWidth': value.imageWidth,
        'readonly': value.readonly,
        'rows': value.rows,
        'col': value.col,
        'items': value.items === undefined ? undefined : ((value.items as Array<any>).map(ItemTOToJSON)),
        'rules': value.rules === undefined ? undefined : ((value.rules as Array<any>).map(RuleTOToJSON)),
        'itemText': value.itemText,
        'itemValue': value.itemValue,
        'returnObject': value.returnObject,
    };
}

