/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ButtonsTO } from './ButtonsTO';
import {
    ButtonsTOFromJSON,
    ButtonsTOFromJSONTyped,
    ButtonsTOToJSON,
} from './ButtonsTO';
import type { GroupTO } from './GroupTO';
import {
    GroupTOFromJSON,
    GroupTOFromJSONTyped,
    GroupTOToJSON,
} from './GroupTO';

/**
 * 
 * @export
 * @interface FormTO
 */
export interface FormTO {
    /**
     * 
     * @type {string}
     * @memberof FormTO
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof FormTO
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof FormTO
     */
    authorizedGroups?: string;
    /**
     * 
     * @type {ButtonsTO}
     * @memberof FormTO
     */
    buttons?: ButtonsTO;
    /**
     * 
     * @type {Array<GroupTO>}
     * @memberof FormTO
     */
    groups?: Array<GroupTO>;
}

/**
 * Check if a given object implements the FormTO interface.
 */
export function instanceOfFormTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "key" in value;

    return isInstance;
}

export function FormTOFromJSON(json: any): FormTO {
    return FormTOFromJSONTyped(json, false);
}

export function FormTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FormTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': json['key'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'authorizedGroups': !exists(json, 'authorizedGroups') ? undefined : json['authorizedGroups'],
        'buttons': !exists(json, 'buttons') ? undefined : ButtonsTOFromJSON(json['buttons']),
        'groups': !exists(json, 'groups') ? undefined : ((json['groups'] as Array<any>).map(GroupTOFromJSON)),
    };
}

export function FormTOToJSON(value?: FormTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'description': value.description,
        'authorizedGroups': value.authorizedGroups,
        'buttons': ButtonsTOToJSON(value.buttons),
        'groups': value.groups === undefined ? undefined : ((value.groups as Array<any>).map(GroupTOToJSON)),
    };
}

