/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAlwMetadataTO
 */
export interface GetAlwMetadataTO {
    /**
     * 
     * @type {string}
     * @memberof GetAlwMetadataTO
     */
    url: string;
}

/**
 * Check if a given object implements the GetAlwMetadataTO interface.
 */
export function instanceOfGetAlwMetadataTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "url" in value;

    return isInstance;
}

export function GetAlwMetadataTOFromJSON(json: any): GetAlwMetadataTO {
    return GetAlwMetadataTOFromJSONTyped(json, false);
}

export function GetAlwMetadataTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAlwMetadataTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': json['url'],
    };
}

export function GetAlwMetadataTOToJSON(value?: GetAlwMetadataTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
    };
}

