/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetMetadataTO
 */
export interface GetMetadataTO {
    /**
     * 
     * @type {string}
     * @memberof GetMetadataTO
     */
    url: string;
}

/**
 * Check if a given object implements the GetMetadataTO interface.
 */
export function instanceOfGetMetadataTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "url" in value;

    return isInstance;
}

export function GetMetadataTOFromJSON(json: any): GetMetadataTO {
    return GetMetadataTOFromJSONTyped(json, false);
}

export function GetMetadataTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMetadataTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': json['url'],
    };
}

export function GetMetadataTOToJSON(value?: GetMetadataTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
    };
}

