/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FormFieldTO } from './FormFieldTO';
import {
    FormFieldTOFromJSON,
    FormFieldTOFromJSONTyped,
    FormFieldTOToJSON,
} from './FormFieldTO';

/**
 * 
 * @export
 * @interface GroupTO
 */
export interface GroupTO {
    /**
     * 
     * @type {string}
     * @memberof GroupTO
     */
    label?: string;
    /**
     * 
     * @type {Array<FormFieldTO>}
     * @memberof GroupTO
     */
    schema?: Array<FormFieldTO>;
}

/**
 * Check if a given object implements the GroupTO interface.
 */
export function instanceOfGroupTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GroupTOFromJSON(json: any): GroupTO {
    return GroupTOFromJSONTyped(json, false);
}

export function GroupTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'label': !exists(json, 'label') ? undefined : json['label'],
        'schema': !exists(json, 'schema') ? undefined : ((json['schema'] as Array<any>).map(FormFieldTOFromJSON)),
    };
}

export function GroupTOToJSON(value?: GroupTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'label': value.label,
        'schema': value.schema === undefined ? undefined : ((value.schema as Array<any>).map(FormFieldTOToJSON)),
    };
}

