/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HistoryTask
 */
export interface HistoryTask {
    /**
     * 
     * @type {string}
     * @memberof HistoryTask
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof HistoryTask
     */
    name?: string;
    /**
     * 
     * @type {Date}
     * @memberof HistoryTask
     */
    endTime?: Date;
}

/**
 * Check if a given object implements the HistoryTask interface.
 */
export function instanceOfHistoryTask(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HistoryTaskFromJSON(json: any): HistoryTask {
    return HistoryTaskFromJSONTyped(json, false);
}

export function HistoryTaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): HistoryTask {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'endTime': !exists(json, 'endTime') ? undefined : (new Date(json['endTime'])),
    };
}

export function HistoryTaskToJSON(value?: HistoryTask | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'endTime': value.endTime === undefined ? undefined : (value.endTime.toISOString()),
    };
}

