/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FormTO } from './FormTO';
import {
    FormTOFromJSON,
    FormTOFromJSONTyped,
    FormTOToJSON,
} from './FormTO';

/**
 * 
 * @export
 * @interface HumanTaskDetailTO
 */
export interface HumanTaskDetailTO {
    /**
     * 
     * @type {string}
     * @memberof HumanTaskDetailTO
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof HumanTaskDetailTO
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof HumanTaskDetailTO
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof HumanTaskDetailTO
     */
    processName: string;
    /**
     * 
     * @type {string}
     * @memberof HumanTaskDetailTO
     */
    processInstanceId: string;
    /**
     * 
     * @type {string}
     * @memberof HumanTaskDetailTO
     */
    assignee?: string;
    /**
     * 
     * @type {string}
     * @memberof HumanTaskDetailTO
     */
    assigneeFormatted?: string;
    /**
     * 
     * @type {string}
     * @memberof HumanTaskDetailTO
     */
    followUpDate?: string;
    /**
     * 
     * @type {Date}
     * @memberof HumanTaskDetailTO
     */
    creationTime: Date;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof HumanTaskDetailTO
     */
    variables?: { [key: string]: object; };
    /**
     * 
     * @type {FormTO}
     * @memberof HumanTaskDetailTO
     */
    form?: FormTO;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof HumanTaskDetailTO
     */
    jsonSchema?: { [key: string]: object; };
    /**
     * 
     * @type {boolean}
     * @memberof HumanTaskDetailTO
     */
    statusDocument?: boolean;
}

/**
 * Check if a given object implements the HumanTaskDetailTO interface.
 */
export function instanceOfHumanTaskDetailTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "processName" in value;
    isInstance = isInstance && "processInstanceId" in value;
    isInstance = isInstance && "creationTime" in value;

    return isInstance;
}

export function HumanTaskDetailTOFromJSON(json: any): HumanTaskDetailTO {
    return HumanTaskDetailTOFromJSONTyped(json, false);
}

export function HumanTaskDetailTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): HumanTaskDetailTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'processName': json['processName'],
        'processInstanceId': json['processInstanceId'],
        'assignee': !exists(json, 'assignee') ? undefined : json['assignee'],
        'assigneeFormatted': !exists(json, 'assigneeFormatted') ? undefined : json['assigneeFormatted'],
        'followUpDate': !exists(json, 'followUpDate') ? undefined : json['followUpDate'],
        'creationTime': (new Date(json['creationTime'])),
        'variables': !exists(json, 'variables') ? undefined : json['variables'],
        'form': !exists(json, 'form') ? undefined : FormTOFromJSON(json['form']),
        'jsonSchema': !exists(json, 'jsonSchema') ? undefined : json['jsonSchema'],
        'statusDocument': !exists(json, 'statusDocument') ? undefined : json['statusDocument'],
    };
}

export function HumanTaskDetailTOToJSON(value?: HumanTaskDetailTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'processName': value.processName,
        'processInstanceId': value.processInstanceId,
        'assignee': value.assignee,
        'assigneeFormatted': value.assigneeFormatted,
        'followUpDate': value.followUpDate,
        'creationTime': (value.creationTime.toISOString()),
        'variables': value.variables,
        'form': FormTOToJSON(value.form),
        'jsonSchema': value.jsonSchema,
        'statusDocument': value.statusDocument,
    };
}

