/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HumanTaskTO
 */
export interface HumanTaskTO {
    /**
     * 
     * @type {string}
     * @memberof HumanTaskTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof HumanTaskTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof HumanTaskTO
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof HumanTaskTO
     */
    processName?: string;
    /**
     * 
     * @type {string}
     * @memberof HumanTaskTO
     */
    assignee?: string;
    /**
     * 
     * @type {string}
     * @memberof HumanTaskTO
     */
    assigneeFormatted?: string;
    /**
     * 
     * @type {string}
     * @memberof HumanTaskTO
     */
    followUpDate?: string;
    /**
     * 
     * @type {Date}
     * @memberof HumanTaskTO
     */
    creationTime?: Date;
}

/**
 * Check if a given object implements the HumanTaskTO interface.
 */
export function instanceOfHumanTaskTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HumanTaskTOFromJSON(json: any): HumanTaskTO {
    return HumanTaskTOFromJSONTyped(json, false);
}

export function HumanTaskTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): HumanTaskTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'processName': !exists(json, 'processName') ? undefined : json['processName'],
        'assignee': !exists(json, 'assignee') ? undefined : json['assignee'],
        'assigneeFormatted': !exists(json, 'assigneeFormatted') ? undefined : json['assigneeFormatted'],
        'followUpDate': !exists(json, 'followUpDate') ? undefined : json['followUpDate'],
        'creationTime': !exists(json, 'creationTime') ? undefined : (new Date(json['creationTime'])),
    };
}

export function HumanTaskTOToJSON(value?: HumanTaskTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'processName': value.processName,
        'assignee': value.assignee,
        'assigneeFormatted': value.assigneeFormatted,
        'followUpDate': value.followUpDate,
        'creationTime': value.creationTime === undefined ? undefined : (value.creationTime.toISOString()),
    };
}

