/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InfoTO
 */
export interface InfoTO {
    /**
     * 
     * @type {string}
     * @memberof InfoTO
     */
    maintenanceInfo1?: string;
    /**
     * 
     * @type {string}
     * @memberof InfoTO
     */
    maintenanceInfo2?: string;
    /**
     * 
     * @type {string}
     * @memberof InfoTO
     */
    environment?: string;
}

/**
 * Check if a given object implements the InfoTO interface.
 */
export function instanceOfInfoTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InfoTOFromJSON(json: any): InfoTO {
    return InfoTOFromJSONTyped(json, false);
}

export function InfoTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): InfoTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'maintenanceInfo1': !exists(json, 'maintenanceInfo1') ? undefined : json['maintenanceInfo1'],
        'maintenanceInfo2': !exists(json, 'maintenanceInfo2') ? undefined : json['maintenanceInfo2'],
        'environment': !exists(json, 'environment') ? undefined : json['environment'],
    };
}

export function InfoTOToJSON(value?: InfoTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'maintenanceInfo1': value.maintenanceInfo1,
        'maintenanceInfo2': value.maintenanceInfo2,
        'environment': value.environment,
    };
}

