/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemTO
 */
export interface ItemTO {
    /**
     * 
     * @type {string}
     * @memberof ItemTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ItemTO
     */
    value?: string;
}

/**
 * Check if a given object implements the ItemTO interface.
 */
export function instanceOfItemTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ItemTOFromJSON(json: any): ItemTO {
    return ItemTOFromJSONTyped(json, false);
}

export function ItemTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function ItemTOToJSON(value?: ItemTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'value': value.value,
    };
}

