/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JsonSchemaTO
 */
export interface JsonSchemaTO {
    /**
     * 
     * @type {string}
     * @memberof JsonSchemaTO
     */
    key: string;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof JsonSchemaTO
     */
    schema: { [key: string]: object; };
}

/**
 * Check if a given object implements the JsonSchemaTO interface.
 */
export function instanceOfJsonSchemaTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "key" in value;
    isInstance = isInstance && "schema" in value;

    return isInstance;
}

export function JsonSchemaTOFromJSON(json: any): JsonSchemaTO {
    return JsonSchemaTOFromJSONTyped(json, false);
}

export function JsonSchemaTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): JsonSchemaTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': json['key'],
        'schema': json['schema'],
    };
}

export function JsonSchemaTOToJSON(value?: JsonSchemaTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'schema': value.schema,
    };
}

