/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MetadataTO
 */
export interface MetadataTO {
    /**
     * 
     * @type {string}
     * @memberof MetadataTO
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof MetadataTO
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof MetadataTO
     */
    url?: string;
}

/**
 * Check if a given object implements the MetadataTO interface.
 */
export function instanceOfMetadataTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function MetadataTOFromJSON(json: any): MetadataTO {
    return MetadataTOFromJSONTyped(json, false);
}

export function MetadataTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetadataTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'url': !exists(json, 'url') ? undefined : json['url'],
    };
}

export function MetadataTOToJSON(value?: MetadataTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'type': value.type,
        'url': value.url,
    };
}

