/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ConfigEntryTO } from './ConfigEntryTO';
import {
    ConfigEntryTOFromJSON,
    ConfigEntryTOFromJSONTyped,
    ConfigEntryTOToJSON,
} from './ConfigEntryTO';
import type { StatusConfigTO } from './StatusConfigTO';
import {
    StatusConfigTOFromJSON,
    StatusConfigTOFromJSONTyped,
    StatusConfigTOToJSON,
} from './StatusConfigTO';

/**
 * 
 * @export
 * @interface ProcessConfigTO
 */
export interface ProcessConfigTO {
    /**
     * 
     * @type {string}
     * @memberof ProcessConfigTO
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof ProcessConfigTO
     */
    statusDokument?: string;
    /**
     * 
     * @type {Array<StatusConfigTO>}
     * @memberof ProcessConfigTO
     */
    statusConfig?: Array<StatusConfigTO>;
    /**
     * 
     * @type {Array<ConfigEntryTO>}
     * @memberof ProcessConfigTO
     */
    configs?: Array<ConfigEntryTO>;
}

/**
 * Check if a given object implements the ProcessConfigTO interface.
 */
export function instanceOfProcessConfigTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "key" in value;

    return isInstance;
}

export function ProcessConfigTOFromJSON(json: any): ProcessConfigTO {
    return ProcessConfigTOFromJSONTyped(json, false);
}

export function ProcessConfigTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessConfigTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': json['key'],
        'statusDokument': !exists(json, 'statusDokument') ? undefined : json['statusDokument'],
        'statusConfig': !exists(json, 'statusConfig') ? undefined : ((json['statusConfig'] as Array<any>).map(StatusConfigTOFromJSON)),
        'configs': !exists(json, 'configs') ? undefined : ((json['configs'] as Array<any>).map(ConfigEntryTOFromJSON)),
    };
}

export function ProcessConfigTOToJSON(value?: ProcessConfigTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'statusDokument': value.statusDokument,
        'statusConfig': value.statusConfig === undefined ? undefined : ((value.statusConfig as Array<any>).map(StatusConfigTOToJSON)),
        'configs': value.configs === undefined ? undefined : ((value.configs as Array<any>).map(ConfigEntryTOToJSON)),
    };
}

