/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RuleTO
 */
export interface RuleTO {
    /**
     * 
     * @type {string}
     * @memberof RuleTO
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof RuleTO
     */
    value?: string;
    /**
     * 
     * @type {string}
     * @memberof RuleTO
     */
    target?: string;
}

/**
 * Check if a given object implements the RuleTO interface.
 */
export function instanceOfRuleTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RuleTOFromJSON(json: any): RuleTO {
    return RuleTOFromJSONTyped(json, false);
}

export function RuleTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RuleTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'value': !exists(json, 'value') ? undefined : json['value'],
        'target': !exists(json, 'target') ? undefined : json['target'],
    };
}

export function RuleTOToJSON(value?: RuleTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'value': value.value,
        'target': value.target,
    };
}

