/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaveTO
 */
export interface SaveTO {
    /**
     * 
     * @type {string}
     * @memberof SaveTO
     */
    taskId: string;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof SaveTO
     */
    variables?: { [key: string]: object; };
}

/**
 * Check if a given object implements the SaveTO interface.
 */
export function instanceOfSaveTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "taskId" in value;

    return isInstance;
}

export function SaveTOFromJSON(json: any): SaveTO {
    return SaveTOFromJSONTyped(json, false);
}

export function SaveTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'taskId': json['taskId'],
        'variables': !exists(json, 'variables') ? undefined : json['variables'],
    };
}

export function SaveTOToJSON(value?: SaveTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'taskId': value.taskId,
        'variables': value.variables,
    };
}

