/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchUserTO
 */
export interface SearchUserTO {
    /**
     * 
     * @type {string}
     * @memberof SearchUserTO
     */
    searchString?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchUserTO
     */
    ous?: string;
}

/**
 * Check if a given object implements the SearchUserTO interface.
 */
export function instanceOfSearchUserTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SearchUserTOFromJSON(json: any): SearchUserTO {
    return SearchUserTOFromJSONTyped(json, false);
}

export function SearchUserTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchUserTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'searchString': !exists(json, 'searchString') ? undefined : json['searchString'],
        'ous': !exists(json, 'ous') ? undefined : json['ous'],
    };
}

export function SearchUserTOToJSON(value?: SearchUserTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'searchString': value.searchString,
        'ous': value.ous,
    };
}

