/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendMessageTO
 */
export interface SendMessageTO {
    /**
     * 
     * @type {string}
     * @memberof SendMessageTO
     */
    instanceId?: string;
    /**
     * 
     * @type {string}
     * @memberof SendMessageTO
     */
    message?: string;
}

/**
 * Check if a given object implements the SendMessageTO interface.
 */
export function instanceOfSendMessageTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SendMessageTOFromJSON(json: any): SendMessageTO {
    return SendMessageTOFromJSONTyped(json, false);
}

export function SendMessageTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendMessageTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'instanceId': !exists(json, 'instanceId') ? undefined : json['instanceId'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function SendMessageTOToJSON(value?: SendMessageTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'instanceId': value.instanceId,
        'message': value.message,
    };
}

