/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceInstanceTO
 */
export interface ServiceInstanceTO {
    /**
     * 
     * @type {string}
     * @memberof ServiceInstanceTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceInstanceTO
     */
    definitionName?: string;
    /**
     * 
     * @type {Date}
     * @memberof ServiceInstanceTO
     */
    startTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ServiceInstanceTO
     */
    endTime?: Date;
    /**
     * 
     * @type {string}
     * @memberof ServiceInstanceTO
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceInstanceTO
     */
    description?: string;
}

/**
 * Check if a given object implements the ServiceInstanceTO interface.
 */
export function instanceOfServiceInstanceTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ServiceInstanceTOFromJSON(json: any): ServiceInstanceTO {
    return ServiceInstanceTOFromJSONTyped(json, false);
}

export function ServiceInstanceTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceInstanceTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'definitionName': !exists(json, 'definitionName') ? undefined : json['definitionName'],
        'startTime': !exists(json, 'startTime') ? undefined : (new Date(json['startTime'])),
        'endTime': !exists(json, 'endTime') ? undefined : (new Date(json['endTime'])),
        'status': !exists(json, 'status') ? undefined : json['status'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function ServiceInstanceTOToJSON(value?: ServiceInstanceTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'definitionName': value.definitionName,
        'startTime': value.startTime === undefined ? undefined : (value.startTime.toISOString()),
        'endTime': value.endTime === undefined ? undefined : (value.endTime.toISOString()),
        'status': value.status,
        'description': value.description,
    };
}

