/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { HistoryTask } from './HistoryTask';
import {
    HistoryTaskFromJSON,
    HistoryTaskFromJSONTyped,
    HistoryTaskToJSON,
} from './HistoryTask';
import type { ProcessConfigTO } from './ProcessConfigTO';
import {
    ProcessConfigTOFromJSON,
    ProcessConfigTOFromJSONTyped,
    ProcessConfigTOToJSON,
} from './ProcessConfigTO';

/**
 * 
 * @export
 * @interface ServiceInstanceDetailTO
 */
export interface ServiceInstanceDetailTO {
    /**
     * 
     * @type {string}
     * @memberof ServiceInstanceDetailTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceInstanceDetailTO
     */
    definitionName?: string;
    /**
     * 
     * @type {Date}
     * @memberof ServiceInstanceDetailTO
     */
    startTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ServiceInstanceDetailTO
     */
    endTime?: Date;
    /**
     * 
     * @type {string}
     * @memberof ServiceInstanceDetailTO
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceInstanceDetailTO
     */
    statusKey?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceInstanceDetailTO
     */
    description?: string;
    /**
     * 
     * @type {ProcessConfigTO}
     * @memberof ServiceInstanceDetailTO
     */
    processConfig?: ProcessConfigTO;
    /**
     * 
     * @type {Array<HistoryTask>}
     * @memberof ServiceInstanceDetailTO
     */
    historyTasks?: Array<HistoryTask>;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof ServiceInstanceDetailTO
     */
    data?: { [key: string]: object; };
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof ServiceInstanceDetailTO
     */
    jsonSchema?: { [key: string]: object; };
}

/**
 * Check if a given object implements the ServiceInstanceDetailTO interface.
 */
export function instanceOfServiceInstanceDetailTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ServiceInstanceDetailTOFromJSON(json: any): ServiceInstanceDetailTO {
    return ServiceInstanceDetailTOFromJSONTyped(json, false);
}

export function ServiceInstanceDetailTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceInstanceDetailTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'definitionName': !exists(json, 'definitionName') ? undefined : json['definitionName'],
        'startTime': !exists(json, 'startTime') ? undefined : (new Date(json['startTime'])),
        'endTime': !exists(json, 'endTime') ? undefined : (new Date(json['endTime'])),
        'status': !exists(json, 'status') ? undefined : json['status'],
        'statusKey': !exists(json, 'statusKey') ? undefined : json['statusKey'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'processConfig': !exists(json, 'processConfig') ? undefined : ProcessConfigTOFromJSON(json['processConfig']),
        'historyTasks': !exists(json, 'historyTasks') ? undefined : ((json['historyTasks'] as Array<any>).map(HistoryTaskFromJSON)),
        'data': !exists(json, 'data') ? undefined : json['data'],
        'jsonSchema': !exists(json, 'jsonSchema') ? undefined : json['jsonSchema'],
    };
}

export function ServiceInstanceDetailTOToJSON(value?: ServiceInstanceDetailTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'definitionName': value.definitionName,
        'startTime': value.startTime === undefined ? undefined : (value.startTime.toISOString()),
        'endTime': value.endTime === undefined ? undefined : (value.endTime.toISOString()),
        'status': value.status,
        'statusKey': value.statusKey,
        'description': value.description,
        'processConfig': ProcessConfigTOToJSON(value.processConfig),
        'historyTasks': value.historyTasks === undefined ? undefined : ((value.historyTasks as Array<any>).map(HistoryTaskToJSON)),
        'data': value.data,
        'jsonSchema': value.jsonSchema,
    };
}

