/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceDefinitionTO
 */
export interface ServiceDefinitionTO {
    /**
     * 
     * @type {string}
     * @memberof ServiceDefinitionTO
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceDefinitionTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceDefinitionTO
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceDefinitionTO
     */
    versionTag?: string;
}

/**
 * Check if a given object implements the ServiceDefinitionTO interface.
 */
export function instanceOfServiceDefinitionTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ServiceDefinitionTOFromJSON(json: any): ServiceDefinitionTO {
    return ServiceDefinitionTOFromJSONTyped(json, false);
}

export function ServiceDefinitionTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceDefinitionTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': !exists(json, 'key') ? undefined : json['key'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'versionTag': !exists(json, 'versionTag') ? undefined : json['versionTag'],
    };
}

export function ServiceDefinitionTOToJSON(value?: ServiceDefinitionTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'name': value.name,
        'description': value.description,
        'versionTag': value.versionTag,
    };
}

