/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FormTO } from './FormTO';
import {
    FormTOFromJSON,
    FormTOFromJSONTyped,
    FormTOToJSON,
} from './FormTO';

/**
 * 
 * @export
 * @interface ServiceDefinitionDetailTO
 */
export interface ServiceDefinitionDetailTO {
    /**
     * 
     * @type {FormTO}
     * @memberof ServiceDefinitionDetailTO
     */
    startForm?: FormTO;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof ServiceDefinitionDetailTO
     */
    jsonSchema?: { [key: string]: object; };
    /**
     * 
     * @type {string}
     * @memberof ServiceDefinitionDetailTO
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceDefinitionDetailTO
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceDefinitionDetailTO
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceDefinitionDetailTO
     */
    versionTag?: string;
}

/**
 * Check if a given object implements the ServiceDefinitionDetailTO interface.
 */
export function instanceOfServiceDefinitionDetailTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "key" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function ServiceDefinitionDetailTOFromJSON(json: any): ServiceDefinitionDetailTO {
    return ServiceDefinitionDetailTOFromJSONTyped(json, false);
}

export function ServiceDefinitionDetailTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceDefinitionDetailTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'startForm': !exists(json, 'startForm') ? undefined : FormTOFromJSON(json['startForm']),
        'jsonSchema': !exists(json, 'jsonSchema') ? undefined : json['jsonSchema'],
        'key': json['key'],
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'versionTag': !exists(json, 'versionTag') ? undefined : json['versionTag'],
    };
}

export function ServiceDefinitionDetailTOToJSON(value?: ServiceDefinitionDetailTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'startForm': FormTOToJSON(value.startForm),
        'jsonSchema': value.jsonSchema,
        'key': value.key,
        'name': value.name,
        'description': value.description,
        'versionTag': value.versionTag,
    };
}

