/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StartInstanceTO
 */
export interface StartInstanceTO {
    /**
     * 
     * @type {string}
     * @memberof StartInstanceTO
     */
    key?: string;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof StartInstanceTO
     */
    variables?: { [key: string]: object; };
}

/**
 * Check if a given object implements the StartInstanceTO interface.
 */
export function instanceOfStartInstanceTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StartInstanceTOFromJSON(json: any): StartInstanceTO {
    return StartInstanceTOFromJSONTyped(json, false);
}

export function StartInstanceTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartInstanceTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': !exists(json, 'key') ? undefined : json['key'],
        'variables': !exists(json, 'variables') ? undefined : json['variables'],
    };
}

export function StartInstanceTOToJSON(value?: StartInstanceTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'variables': value.variables,
    };
}

