/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StatusConfigTO
 */
export interface StatusConfigTO {
    /**
     * 
     * @type {string}
     * @memberof StatusConfigTO
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof StatusConfigTO
     */
    label: string;
    /**
     * 
     * @type {number}
     * @memberof StatusConfigTO
     */
    position: number;
}

/**
 * Check if a given object implements the StatusConfigTO interface.
 */
export function instanceOfStatusConfigTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "key" in value;
    isInstance = isInstance && "label" in value;
    isInstance = isInstance && "position" in value;

    return isInstance;
}

export function StatusConfigTOFromJSON(json: any): StatusConfigTO {
    return StatusConfigTOFromJSONTyped(json, false);
}

export function StatusConfigTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusConfigTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': json['key'],
        'label': json['label'],
        'position': json['position'],
    };
}

export function StatusConfigTOToJSON(value?: StatusConfigTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'label': value.label,
        'position': value.position,
    };
}

