/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StatusDokumentTO
 */
export interface StatusDokumentTO {
    /**
     * 
     * @type {string}
     * @memberof StatusDokumentTO
     */
    name?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof StatusDokumentTO
     */
    data?: Array<string>;
}

/**
 * Check if a given object implements the StatusDokumentTO interface.
 */
export function instanceOfStatusDokumentTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StatusDokumentTOFromJSON(json: any): StatusDokumentTO {
    return StatusDokumentTOFromJSONTyped(json, false);
}

export function StatusDokumentTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusDokumentTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'data': !exists(json, 'data') ? undefined : json['data'],
    };
}

export function StatusDokumentTOToJSON(value?: StatusDokumentTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'data': value.data,
    };
}

