/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserTO
 */
export interface UserTO {
    /**
     * 
     * @type {string}
     * @memberof UserTO
     */
    lhmObjectId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserTO
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof UserTO
     */
    forename?: string;
    /**
     * 
     * @type {string}
     * @memberof UserTO
     */
    surname?: string;
    /**
     * 
     * @type {string}
     * @memberof UserTO
     */
    ou?: string;
    /**
     * 
     * @type {string}
     * @memberof UserTO
     */
    department?: string;
    /**
     * 
     * @type {string}
     * @memberof UserTO
     */
    email?: string;
}

/**
 * Check if a given object implements the UserTO interface.
 */
export function instanceOfUserTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserTOFromJSON(json: any): UserTO {
    return UserTOFromJSONTyped(json, false);
}

export function UserTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lhmObjectId': !exists(json, 'lhmObjectId') ? undefined : json['lhmObjectId'],
        'username': !exists(json, 'username') ? undefined : json['username'],
        'forename': !exists(json, 'forename') ? undefined : json['forename'],
        'surname': !exists(json, 'surname') ? undefined : json['surname'],
        'ou': !exists(json, 'ou') ? undefined : json['ou'],
        'department': !exists(json, 'department') ? undefined : json['department'],
        'email': !exists(json, 'email') ? undefined : json['email'],
    };
}

export function UserTOToJSON(value?: UserTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lhmObjectId': value.lhmObjectId,
        'username': value.username,
        'forename': value.forename,
        'surname': value.surname,
        'ou': value.ou,
        'department': value.department,
        'email': value.email,
    };
}

