/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AlwMetaDataTO,
  GetAlwMetadataTO,
} from '../models';
import {
    AlwMetaDataTOFromJSON,
    AlwMetaDataTOToJSON,
    GetAlwMetadataTOFromJSON,
    GetAlwMetadataTOToJSON,
} from '../models';

export interface GetMetadataRequest {
    getAlwMetadataTO: GetAlwMetadataTO;
}

/**
 * 
 */
export class AlwDmsRestControllerApi extends runtime.BaseAPI {

    /**
     */
    async getMetadataRaw(requestParameters: GetMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AlwMetaDataTO>> {
        if (requestParameters.getAlwMetadataTO === null || requestParameters.getAlwMetadataTO === undefined) {
            throw new runtime.RequiredError('getAlwMetadataTO','Required parameter requestParameters.getAlwMetadataTO was null or undefined when calling getMetadata.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("spring_oauth", []);
        }

        const response = await this.request({
            path: `/rest/alwdms/metadata`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GetAlwMetadataTOToJSON(requestParameters.getAlwMetadataTO),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AlwMetaDataTOFromJSON(jsonValue));
    }

    /**
     */
    async getMetadata(requestParameters: GetMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AlwMetaDataTO> {
        const response = await this.getMetadataRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
