/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DeploymentDto,
  DeploymentStatusDto,
} from '../models';
import {
    DeploymentDtoFromJSON,
    DeploymentDtoToJSON,
    DeploymentStatusDtoFromJSON,
    DeploymentStatusDtoToJSON,
} from '../models';

export interface DeployArtifactsRequest {
    deploymentDto: DeploymentDto;
}

/**
 * 
 */
export class DeploymentControllerApi extends runtime.BaseAPI {

    /**
     */
    async deployArtifactsRaw(requestParameters: DeployArtifactsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeploymentStatusDto>> {
        if (requestParameters.deploymentDto === null || requestParameters.deploymentDto === undefined) {
            throw new runtime.RequiredError('deploymentDto','Required parameter requestParameters.deploymentDto was null or undefined when calling deployArtifacts.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("spring_oauth", []);
        }

        const response = await this.request({
            path: `/rest/deployment`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeploymentDtoToJSON(requestParameters.deploymentDto),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeploymentStatusDtoFromJSON(jsonValue));
    }

    /**
     */
    async deployArtifacts(requestParameters: DeployArtifactsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeploymentStatusDto> {
        const response = await this.deployArtifactsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
