/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetMetadataTO,
  MetadataTO,
} from '../models';
import {
    GetMetadataTOFromJSON,
    GetMetadataTOToJSON,
    MetadataTOFromJSON,
    MetadataTOToJSON,
} from '../models';

export interface GetMetaDataRequest {
    getMetadataTO: GetMetadataTO;
}

/**
 * 
 */
export class DmsRestControllerApi extends runtime.BaseAPI {

    /**
     */
    async getMetaDataRaw(requestParameters: GetMetaDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MetadataTO>> {
        if (requestParameters.getMetadataTO === null || requestParameters.getMetadataTO === undefined) {
            throw new runtime.RequiredError('getMetadataTO','Required parameter requestParameters.getMetadataTO was null or undefined when calling getMetaData.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("spring_oauth", []);
        }

        const response = await this.request({
            path: `/rest/dms/metadata`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GetMetadataTOToJSON(requestParameters.getMetadataTO),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MetadataTOFromJSON(jsonValue));
    }

    /**
     */
    async getMetaData(requestParameters: GetMetaDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MetadataTO> {
        const response = await this.getMetaDataRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
