/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  StatusDokumentTO,
} from '../models';
import {
    StatusDokumentTOFromJSON,
    StatusDokumentTOToJSON,
} from '../models';

export interface GetStatusDokumentForTaskRequest {
    id: string;
}

/**
 * 
 */
export class DocumentRestControllerApi extends runtime.BaseAPI {

    /**
     */
    async getStatusDokumentForTaskRaw(requestParameters: GetStatusDokumentForTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StatusDokumentTO>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling getStatusDokumentForTask.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("spring_oauth", []);
        }

        const response = await this.request({
            path: `/rest/document/task/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StatusDokumentTOFromJSON(jsonValue));
    }

    /**
     */
    async getStatusDokumentForTask(requestParameters: GetStatusDokumentForTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StatusDokumentTO> {
        const response = await this.getStatusDokumentForTaskRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
