/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FormTO,
} from '../models';
import {
    FormTOFromJSON,
    FormTOToJSON,
} from '../models';

export interface CreateFormRequest {
    formTO: FormTO;
}

export interface GetFormRequest {
    key: string;
}

export interface UpdateFormRequest {
    key: string;
    formTO: FormTO;
}

/**
 * 
 */
export class FormRestControllerApi extends runtime.BaseAPI {

    /**
     */
    async createFormRaw(requestParameters: CreateFormRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FormTO>> {
        if (requestParameters.formTO === null || requestParameters.formTO === undefined) {
            throw new runtime.RequiredError('formTO','Required parameter requestParameters.formTO was null or undefined when calling createForm.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("spring_oauth", []);
        }

        const response = await this.request({
            path: `/rest/form`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FormTOToJSON(requestParameters.formTO),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FormTOFromJSON(jsonValue));
    }

    /**
     */
    async createForm(requestParameters: CreateFormRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FormTO> {
        const response = await this.createFormRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getFormRaw(requestParameters: GetFormRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FormTO>> {
        if (requestParameters.key === null || requestParameters.key === undefined) {
            throw new runtime.RequiredError('key','Required parameter requestParameters.key was null or undefined when calling getForm.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("spring_oauth", []);
        }

        const response = await this.request({
            path: `/rest/form/{key}`.replace(`{${"key"}}`, encodeURIComponent(String(requestParameters.key))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FormTOFromJSON(jsonValue));
    }

    /**
     */
    async getForm(requestParameters: GetFormRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FormTO> {
        const response = await this.getFormRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getFormsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<FormTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("spring_oauth", []);
        }

        const response = await this.request({
            path: `/rest/form`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FormTOFromJSON));
    }

    /**
     */
    async getForms(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<FormTO>> {
        const response = await this.getFormsRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async updateFormRaw(requestParameters: UpdateFormRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FormTO>> {
        if (requestParameters.key === null || requestParameters.key === undefined) {
            throw new runtime.RequiredError('key','Required parameter requestParameters.key was null or undefined when calling updateForm.');
        }

        if (requestParameters.formTO === null || requestParameters.formTO === undefined) {
            throw new runtime.RequiredError('formTO','Required parameter requestParameters.formTO was null or undefined when calling updateForm.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("spring_oauth", []);
        }

        const response = await this.request({
            path: `/rest/form/{key}`.replace(`{${"key"}}`, encodeURIComponent(String(requestParameters.key))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: FormTOToJSON(requestParameters.formTO),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FormTOFromJSON(jsonValue));
    }

    /**
     */
    async updateForm(requestParameters: UpdateFormRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FormTO> {
        const response = await this.updateFormRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
