/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CompleteTO,
  FollowUpTO,
  HumanTaskDetailTO,
  HumanTaskTO,
  SaveTO,
} from '../models';
import {
    CompleteTOFromJSON,
    CompleteTOToJSON,
    FollowUpTOFromJSON,
    FollowUpTOToJSON,
    HumanTaskDetailTOFromJSON,
    HumanTaskDetailTOToJSON,
    HumanTaskTOFromJSON,
    HumanTaskTOToJSON,
    SaveTOFromJSON,
    SaveTOToJSON,
} from '../models';

export interface AssignTaskRequest {
    id: string;
}

export interface CancelTaskRequest {
    id: string;
}

export interface CompleteTaskRequest {
    completeTO: CompleteTO;
}

export interface FollowUpTaskRequest {
    followUpTO: FollowUpTO;
}

export interface GetTaskDetailRequest {
    id: string;
}

export interface SaveTaskRequest {
    saveTO: SaveTO;
}

/**
 * 
 */
export class HumanTaskRestControllerApi extends runtime.BaseAPI {

    /**
     */
    async assignTaskRaw(requestParameters: AssignTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling assignTask.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("spring_oauth", []);
        }

        const response = await this.request({
            path: `/rest/task/assign/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async assignTask(requestParameters: AssignTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.assignTaskRaw(requestParameters, initOverrides);
    }

    /**
     */
    async cancelTaskRaw(requestParameters: CancelTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling cancelTask.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("spring_oauth", []);
        }

        const response = await this.request({
            path: `/rest/task/cancel/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async cancelTask(requestParameters: CancelTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.cancelTaskRaw(requestParameters, initOverrides);
    }

    /**
     */
    async completeTaskRaw(requestParameters: CompleteTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.completeTO === null || requestParameters.completeTO === undefined) {
            throw new runtime.RequiredError('completeTO','Required parameter requestParameters.completeTO was null or undefined when calling completeTask.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("spring_oauth", []);
        }

        const response = await this.request({
            path: `/rest/task`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CompleteTOToJSON(requestParameters.completeTO),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async completeTask(requestParameters: CompleteTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.completeTaskRaw(requestParameters, initOverrides);
    }

    /**
     */
    async followUpTaskRaw(requestParameters: FollowUpTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.followUpTO === null || requestParameters.followUpTO === undefined) {
            throw new runtime.RequiredError('followUpTO','Required parameter requestParameters.followUpTO was null or undefined when calling followUpTask.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("spring_oauth", []);
        }

        const response = await this.request({
            path: `/rest/task/followup`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FollowUpTOToJSON(requestParameters.followUpTO),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async followUpTask(requestParameters: FollowUpTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.followUpTaskRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getAssignedGroupTasksRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<HumanTaskTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("spring_oauth", []);
        }

        const response = await this.request({
            path: `/rest/task/group/assigned`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(HumanTaskTOFromJSON));
    }

    /**
     */
    async getAssignedGroupTasks(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<HumanTaskTO>> {
        const response = await this.getAssignedGroupTasksRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getOpenGroupTasksRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<HumanTaskTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("spring_oauth", []);
        }

        const response = await this.request({
            path: `/rest/task/group/open`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(HumanTaskTOFromJSON));
    }

    /**
     */
    async getOpenGroupTasks(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<HumanTaskTO>> {
        const response = await this.getOpenGroupTasksRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getTaskDetailRaw(requestParameters: GetTaskDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HumanTaskDetailTO>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling getTaskDetail.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("spring_oauth", []);
        }

        const response = await this.request({
            path: `/rest/task/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HumanTaskDetailTOFromJSON(jsonValue));
    }

    /**
     */
    async getTaskDetail(requestParameters: GetTaskDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HumanTaskDetailTO> {
        const response = await this.getTaskDetailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getTasksRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<HumanTaskTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("spring_oauth", []);
        }

        const response = await this.request({
            path: `/rest/task`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(HumanTaskTOFromJSON));
    }

    /**
     */
    async getTasks(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<HumanTaskTO>> {
        const response = await this.getTasksRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async saveTaskRaw(requestParameters: SaveTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HumanTaskDetailTO>> {
        if (requestParameters.saveTO === null || requestParameters.saveTO === undefined) {
            throw new runtime.RequiredError('saveTO','Required parameter requestParameters.saveTO was null or undefined when calling saveTask.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("spring_oauth", []);
        }

        const response = await this.request({
            path: `/rest/task`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SaveTOToJSON(requestParameters.saveTO),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HumanTaskDetailTOFromJSON(jsonValue));
    }

    /**
     */
    async saveTask(requestParameters: SaveTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HumanTaskDetailTO> {
        const response = await this.saveTaskRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
