/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SendMessageTO,
} from '../models';
import {
    SendMessageTOFromJSON,
    SendMessageTOToJSON,
} from '../models';

export interface SendMessageRequest {
    sendMessageTO: SendMessageTO;
}

/**
 * 
 */
export class MessageControllerApi extends runtime.BaseAPI {

    /**
     */
    async sendMessageRaw(requestParameters: SendMessageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.sendMessageTO === null || requestParameters.sendMessageTO === undefined) {
            throw new runtime.RequiredError('sendMessageTO','Required parameter requestParameters.sendMessageTO was null or undefined when calling sendMessage.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("spring_oauth", []);
        }

        const response = await this.request({
            path: `/rest/input/message/send/message`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SendMessageTOToJSON(requestParameters.sendMessageTO),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async sendMessage(requestParameters: SendMessageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.sendMessageRaw(requestParameters, initOverrides);
    }

}
