/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ProcessConfigTO,
} from '../models';
import {
    ProcessConfigTOFromJSON,
    ProcessConfigTOToJSON,
} from '../models';

export interface CreateConfigRequest {
    processConfigTO: ProcessConfigTO;
}

export interface GetConfigRequest {
    key: string;
}

/**
 * 
 */
export class ProcessConfigurationControllerApi extends runtime.BaseAPI {

    /**
     */
    async createConfigRaw(requestParameters: CreateConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProcessConfigTO>> {
        if (requestParameters.processConfigTO === null || requestParameters.processConfigTO === undefined) {
            throw new runtime.RequiredError('processConfigTO','Required parameter requestParameters.processConfigTO was null or undefined when calling createConfig.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("spring_oauth", []);
        }

        const response = await this.request({
            path: `/rest/processconfig`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProcessConfigTOToJSON(requestParameters.processConfigTO),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProcessConfigTOFromJSON(jsonValue));
    }

    /**
     */
    async createConfig(requestParameters: CreateConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProcessConfigTO> {
        const response = await this.createConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getConfigRaw(requestParameters: GetConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProcessConfigTO>> {
        if (requestParameters.key === null || requestParameters.key === undefined) {
            throw new runtime.RequiredError('key','Required parameter requestParameters.key was null or undefined when calling getConfig.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("spring_oauth", []);
        }

        const response = await this.request({
            path: `/rest/processconfig/{key}`.replace(`{${"key"}}`, encodeURIComponent(String(requestParameters.key))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProcessConfigTOFromJSON(jsonValue));
    }

    /**
     */
    async getConfig(requestParameters: GetConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProcessConfigTO> {
        const response = await this.getConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
