/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  JsonSchemaTO,
} from '../models';
import {
    JsonSchemaTOFromJSON,
    JsonSchemaTOToJSON,
} from '../models';

export interface CreateJsonSchemaRequest {
    jsonSchemaTO: JsonSchemaTO;
}

export interface GetJsonSchemaRequest {
    key: string;
}

/**
 * 
 */
export class SchemaRestControllerApi extends runtime.BaseAPI {

    /**
     * create a new json schema
     */
    async createJsonSchemaRaw(requestParameters: CreateJsonSchemaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JsonSchemaTO>> {
        if (requestParameters.jsonSchemaTO === null || requestParameters.jsonSchemaTO === undefined) {
            throw new runtime.RequiredError('jsonSchemaTO','Required parameter requestParameters.jsonSchemaTO was null or undefined when calling createJsonSchema.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("spring_oauth", []);
        }

        const response = await this.request({
            path: `/rest/jsonschema`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: JsonSchemaTOToJSON(requestParameters.jsonSchemaTO),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JsonSchemaTOFromJSON(jsonValue));
    }

    /**
     * create a new json schema
     */
    async createJsonSchema(requestParameters: CreateJsonSchemaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JsonSchemaTO> {
        const response = await this.createJsonSchemaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * get json schema by key
     */
    async getJsonSchemaRaw(requestParameters: GetJsonSchemaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JsonSchemaTO>> {
        if (requestParameters.key === null || requestParameters.key === undefined) {
            throw new runtime.RequiredError('key','Required parameter requestParameters.key was null or undefined when calling getJsonSchema.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("spring_oauth", []);
        }

        const response = await this.request({
            path: `/rest/jsonschema/{key}`.replace(`{${"key"}}`, encodeURIComponent(String(requestParameters.key))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JsonSchemaTOFromJSON(jsonValue));
    }

    /**
     * get json schema by key
     */
    async getJsonSchema(requestParameters: GetJsonSchemaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JsonSchemaTO> {
        const response = await this.getJsonSchemaRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
