/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface GetFileNames2Request {
    instanceId: string;
    filePath: string;
}

export interface GetPresignedUrlForFileDeletion2Request {
    instanceId: string;
    filename: string;
    filePath: string;
}

export interface GetPresignedUrlForFileDownload2Request {
    instanceId: string;
    fileName: string;
    filePath: string;
}

export interface GetPresignedUrlForFileUpload2Request {
    instanceId: string;
    filename: string;
    filePath: string;
}

/**
 * 
 */
export class ServiceInstanceFileRestControllerApi extends runtime.BaseAPI {

    /**
     */
    async getFileNames2Raw(requestParameters: GetFileNames2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        if (requestParameters.instanceId === null || requestParameters.instanceId === undefined) {
            throw new runtime.RequiredError('instanceId','Required parameter requestParameters.instanceId was null or undefined when calling getFileNames2.');
        }

        if (requestParameters.filePath === null || requestParameters.filePath === undefined) {
            throw new runtime.RequiredError('filePath','Required parameter requestParameters.filePath was null or undefined when calling getFileNames2.');
        }

        const queryParameters: any = {};

        if (requestParameters.filePath !== undefined) {
            queryParameters['filePath'] = requestParameters.filePath;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("spring_oauth", []);
        }

        const response = await this.request({
            path: `/rest/service/instance/file/{instanceId}`.replace(`{${"instanceId"}}`, encodeURIComponent(String(requestParameters.instanceId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async getFileNames2(requestParameters: GetFileNames2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.getFileNames2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getPresignedUrlForFileDeletion2Raw(requestParameters: GetPresignedUrlForFileDeletion2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters.instanceId === null || requestParameters.instanceId === undefined) {
            throw new runtime.RequiredError('instanceId','Required parameter requestParameters.instanceId was null or undefined when calling getPresignedUrlForFileDeletion2.');
        }

        if (requestParameters.filename === null || requestParameters.filename === undefined) {
            throw new runtime.RequiredError('filename','Required parameter requestParameters.filename was null or undefined when calling getPresignedUrlForFileDeletion2.');
        }

        if (requestParameters.filePath === null || requestParameters.filePath === undefined) {
            throw new runtime.RequiredError('filePath','Required parameter requestParameters.filePath was null or undefined when calling getPresignedUrlForFileDeletion2.');
        }

        const queryParameters: any = {};

        if (requestParameters.filePath !== undefined) {
            queryParameters['filePath'] = requestParameters.filePath;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("spring_oauth", []);
        }

        const response = await this.request({
            path: `/rest/service/instance/file/{instanceId}/{filename}`.replace(`{${"instanceId"}}`, encodeURIComponent(String(requestParameters.instanceId))).replace(`{${"filename"}}`, encodeURIComponent(String(requestParameters.filename))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     */
    async getPresignedUrlForFileDeletion2(requestParameters: GetPresignedUrlForFileDeletion2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.getPresignedUrlForFileDeletion2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getPresignedUrlForFileDownload2Raw(requestParameters: GetPresignedUrlForFileDownload2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters.instanceId === null || requestParameters.instanceId === undefined) {
            throw new runtime.RequiredError('instanceId','Required parameter requestParameters.instanceId was null or undefined when calling getPresignedUrlForFileDownload2.');
        }

        if (requestParameters.fileName === null || requestParameters.fileName === undefined) {
            throw new runtime.RequiredError('fileName','Required parameter requestParameters.fileName was null or undefined when calling getPresignedUrlForFileDownload2.');
        }

        if (requestParameters.filePath === null || requestParameters.filePath === undefined) {
            throw new runtime.RequiredError('filePath','Required parameter requestParameters.filePath was null or undefined when calling getPresignedUrlForFileDownload2.');
        }

        const queryParameters: any = {};

        if (requestParameters.filePath !== undefined) {
            queryParameters['filePath'] = requestParameters.filePath;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("spring_oauth", []);
        }

        const response = await this.request({
            path: `/rest/service/instance/file/{instanceId}/{fileName}`.replace(`{${"instanceId"}}`, encodeURIComponent(String(requestParameters.instanceId))).replace(`{${"fileName"}}`, encodeURIComponent(String(requestParameters.fileName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     */
    async getPresignedUrlForFileDownload2(requestParameters: GetPresignedUrlForFileDownload2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.getPresignedUrlForFileDownload2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getPresignedUrlForFileUpload2Raw(requestParameters: GetPresignedUrlForFileUpload2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters.instanceId === null || requestParameters.instanceId === undefined) {
            throw new runtime.RequiredError('instanceId','Required parameter requestParameters.instanceId was null or undefined when calling getPresignedUrlForFileUpload2.');
        }

        if (requestParameters.filename === null || requestParameters.filename === undefined) {
            throw new runtime.RequiredError('filename','Required parameter requestParameters.filename was null or undefined when calling getPresignedUrlForFileUpload2.');
        }

        if (requestParameters.filePath === null || requestParameters.filePath === undefined) {
            throw new runtime.RequiredError('filePath','Required parameter requestParameters.filePath was null or undefined when calling getPresignedUrlForFileUpload2.');
        }

        const queryParameters: any = {};

        if (requestParameters.filePath !== undefined) {
            queryParameters['filePath'] = requestParameters.filePath;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("spring_oauth", []);
        }

        const response = await this.request({
            path: `/rest/service/instance/file/{instanceId}/{filename}`.replace(`{${"instanceId"}}`, encodeURIComponent(String(requestParameters.instanceId))).replace(`{${"filename"}}`, encodeURIComponent(String(requestParameters.filename))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     */
    async getPresignedUrlForFileUpload2(requestParameters: GetPresignedUrlForFileUpload2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.getPresignedUrlForFileUpload2Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
