/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface GetFileNames1Request {
    definitionKey: string;
    filePath: string;
}

export interface GetPresignedUrlForFileDeletion1Request {
    definitionKey: string;
    filename: string;
    filePath: string;
}

export interface GetPresignedUrlForFileDownload1Request {
    definitionKey: string;
    fileName: string;
    filePath: string;
}

export interface GetPresignedUrlForFileUpload1Request {
    definitionKey: string;
    filename: string;
    filePath: string;
}

/**
 * 
 */
export class ServiceStartFileRestControllerApi extends runtime.BaseAPI {

    /**
     */
    async getFileNames1Raw(requestParameters: GetFileNames1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        if (requestParameters.definitionKey === null || requestParameters.definitionKey === undefined) {
            throw new runtime.RequiredError('definitionKey','Required parameter requestParameters.definitionKey was null or undefined when calling getFileNames1.');
        }

        if (requestParameters.filePath === null || requestParameters.filePath === undefined) {
            throw new runtime.RequiredError('filePath','Required parameter requestParameters.filePath was null or undefined when calling getFileNames1.');
        }

        const queryParameters: any = {};

        if (requestParameters.filePath !== undefined) {
            queryParameters['filePath'] = requestParameters.filePath;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("spring_oauth", []);
        }

        const response = await this.request({
            path: `/rest/service/start/file/{definitionKey}`.replace(`{${"definitionKey"}}`, encodeURIComponent(String(requestParameters.definitionKey))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async getFileNames1(requestParameters: GetFileNames1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.getFileNames1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getPresignedUrlForFileDeletion1Raw(requestParameters: GetPresignedUrlForFileDeletion1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters.definitionKey === null || requestParameters.definitionKey === undefined) {
            throw new runtime.RequiredError('definitionKey','Required parameter requestParameters.definitionKey was null or undefined when calling getPresignedUrlForFileDeletion1.');
        }

        if (requestParameters.filename === null || requestParameters.filename === undefined) {
            throw new runtime.RequiredError('filename','Required parameter requestParameters.filename was null or undefined when calling getPresignedUrlForFileDeletion1.');
        }

        if (requestParameters.filePath === null || requestParameters.filePath === undefined) {
            throw new runtime.RequiredError('filePath','Required parameter requestParameters.filePath was null or undefined when calling getPresignedUrlForFileDeletion1.');
        }

        const queryParameters: any = {};

        if (requestParameters.filePath !== undefined) {
            queryParameters['filePath'] = requestParameters.filePath;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("spring_oauth", []);
        }

        const response = await this.request({
            path: `/rest/service/start/file/{definitionKey}/{filename}`.replace(`{${"definitionKey"}}`, encodeURIComponent(String(requestParameters.definitionKey))).replace(`{${"filename"}}`, encodeURIComponent(String(requestParameters.filename))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     */
    async getPresignedUrlForFileDeletion1(requestParameters: GetPresignedUrlForFileDeletion1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.getPresignedUrlForFileDeletion1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getPresignedUrlForFileDownload1Raw(requestParameters: GetPresignedUrlForFileDownload1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters.definitionKey === null || requestParameters.definitionKey === undefined) {
            throw new runtime.RequiredError('definitionKey','Required parameter requestParameters.definitionKey was null or undefined when calling getPresignedUrlForFileDownload1.');
        }

        if (requestParameters.fileName === null || requestParameters.fileName === undefined) {
            throw new runtime.RequiredError('fileName','Required parameter requestParameters.fileName was null or undefined when calling getPresignedUrlForFileDownload1.');
        }

        if (requestParameters.filePath === null || requestParameters.filePath === undefined) {
            throw new runtime.RequiredError('filePath','Required parameter requestParameters.filePath was null or undefined when calling getPresignedUrlForFileDownload1.');
        }

        const queryParameters: any = {};

        if (requestParameters.filePath !== undefined) {
            queryParameters['filePath'] = requestParameters.filePath;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("spring_oauth", []);
        }

        const response = await this.request({
            path: `/rest/service/start/file/{definitionKey}/{fileName}`.replace(`{${"definitionKey"}}`, encodeURIComponent(String(requestParameters.definitionKey))).replace(`{${"fileName"}}`, encodeURIComponent(String(requestParameters.fileName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     */
    async getPresignedUrlForFileDownload1(requestParameters: GetPresignedUrlForFileDownload1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.getPresignedUrlForFileDownload1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getPresignedUrlForFileUpload1Raw(requestParameters: GetPresignedUrlForFileUpload1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters.definitionKey === null || requestParameters.definitionKey === undefined) {
            throw new runtime.RequiredError('definitionKey','Required parameter requestParameters.definitionKey was null or undefined when calling getPresignedUrlForFileUpload1.');
        }

        if (requestParameters.filename === null || requestParameters.filename === undefined) {
            throw new runtime.RequiredError('filename','Required parameter requestParameters.filename was null or undefined when calling getPresignedUrlForFileUpload1.');
        }

        if (requestParameters.filePath === null || requestParameters.filePath === undefined) {
            throw new runtime.RequiredError('filePath','Required parameter requestParameters.filePath was null or undefined when calling getPresignedUrlForFileUpload1.');
        }

        const queryParameters: any = {};

        if (requestParameters.filePath !== undefined) {
            queryParameters['filePath'] = requestParameters.filePath;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("spring_oauth", []);
        }

        const response = await this.request({
            path: `/rest/service/start/file/{definitionKey}/{filename}`.replace(`{${"definitionKey"}}`, encodeURIComponent(String(requestParameters.definitionKey))).replace(`{${"filename"}}`, encodeURIComponent(String(requestParameters.filename))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     */
    async getPresignedUrlForFileUpload1(requestParameters: GetPresignedUrlForFileUpload1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.getPresignedUrlForFileUpload1Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
