/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ServiceInstanceDetailTO,
  ServiceInstanceTO,
} from '../models';
import {
    ServiceInstanceDetailTOFromJSON,
    ServiceInstanceDetailTOToJSON,
    ServiceInstanceTOFromJSON,
    ServiceInstanceTOToJSON,
} from '../models';

export interface GetProcessInstanceDetailRequest {
    id: string;
}

/**
 * 
 */
export class ServiceInstanceControllerApi extends runtime.BaseAPI {

    /**
     */
    async getAssignedInstancesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ServiceInstanceTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("spring_oauth", []);
        }

        const response = await this.request({
            path: `/rest/service/instance`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ServiceInstanceTOFromJSON));
    }

    /**
     */
    async getAssignedInstances(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ServiceInstanceTO>> {
        const response = await this.getAssignedInstancesRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getProcessInstanceDetailRaw(requestParameters: GetProcessInstanceDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServiceInstanceDetailTO>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling getProcessInstanceDetail.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("spring_oauth", []);
        }

        const response = await this.request({
            path: `/rest/service/instance/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServiceInstanceDetailTOFromJSON(jsonValue));
    }

    /**
     */
    async getProcessInstanceDetail(requestParameters: GetProcessInstanceDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServiceInstanceDetailTO> {
        const response = await this.getProcessInstanceDetailRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
