/* tslint:disable */
/* eslint-disable */
/**
 * DigiWF API
 * DigiWF - Plattform zur Digitalisierung von Workflows bei der LHM
 *
 * The version of the OpenAPI document: 0.34.0-SNAPSHOT
 * Contact: itm.digiwf@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ServiceDefinitionDetailTO,
  ServiceDefinitionTO,
  StartInstanceTO,
} from '../models';
import {
    ServiceDefinitionDetailTOFromJSON,
    ServiceDefinitionDetailTOToJSON,
    ServiceDefinitionTOFromJSON,
    ServiceDefinitionTOToJSON,
    StartInstanceTOFromJSON,
    StartInstanceTOToJSON,
} from '../models';

export interface GetServiceDefinitionRequest {
    key: string;
}

export interface StartInstanceRequest {
    startInstanceTO: StartInstanceTO;
}

/**
 * 
 */
export class ServiceDefinitionControllerApi extends runtime.BaseAPI {

    /**
     * Get a specific service definition
     */
    async getServiceDefinitionRaw(requestParameters: GetServiceDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServiceDefinitionDetailTO>> {
        if (requestParameters.key === null || requestParameters.key === undefined) {
            throw new runtime.RequiredError('key','Required parameter requestParameters.key was null or undefined when calling getServiceDefinition.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("spring_oauth", []);
        }

        const response = await this.request({
            path: `/rest/service/definition/{key}`.replace(`{${"key"}}`, encodeURIComponent(String(requestParameters.key))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServiceDefinitionDetailTOFromJSON(jsonValue));
    }

    /**
     * Get a specific service definition
     */
    async getServiceDefinition(requestParameters: GetServiceDefinitionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServiceDefinitionDetailTO> {
        const response = await this.getServiceDefinitionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * load all available service definitions
     */
    async getServiceDefinitionsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ServiceDefinitionTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("spring_oauth", []);
        }

        const response = await this.request({
            path: `/rest/service/definition`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ServiceDefinitionTOFromJSON));
    }

    /**
     * load all available service definitions
     */
    async getServiceDefinitions(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ServiceDefinitionTO>> {
        const response = await this.getServiceDefinitionsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Start a specific service
     */
    async startInstanceRaw(requestParameters: StartInstanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.startInstanceTO === null || requestParameters.startInstanceTO === undefined) {
            throw new runtime.RequiredError('startInstanceTO','Required parameter requestParameters.startInstanceTO was null or undefined when calling startInstance.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("spring_oauth", []);
        }

        const response = await this.request({
            path: `/rest/service/definition`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StartInstanceTOToJSON(requestParameters.startInstanceTO),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Start a specific service
     */
    async startInstance(requestParameters: StartInstanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.startInstanceRaw(requestParameters, initOverrides);
    }

}
