// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DwfDialogButton: typeof import('./src/components/common/DwfDialogButton.vue')['default']
    DwfDialogListItem: typeof import('./src/components/common/DwfDialogListItem.vue')['default']
    DwfDraggableListItem: typeof import('./src/components/common/DwfDraggableListItem.vue')['default']
    DwfEditContainerModal: typeof import('./src/components/modals/DwfEditContainerModal.vue')['default']
    DwfEditFormFieldModal: typeof import('./src/components/modals/DwfEditFormFieldModal.vue')['default']
    DwfEditSectionModal: typeof import('./src/components/modals/DwfEditSectionModal.vue')['default']
    DwfFormArrayObject: typeof import('./src/components/DwfFormArrayObject.vue')['default']
    DwfFormBuilder: typeof import('./src/components/DwfFormBuilder.vue')['default']
    DwfFormBuilderElements: typeof import('./src/components/DwfFormBuilderElements.vue')['default']
    DwfFormContainer: typeof import('./src/components/DwfFormContainer.vue')['default']
    DwfFormField: typeof import('./src/components/DwfFormField.vue')['default']
    DwfFormObject: typeof import('./src/components/DwfFormObject.vue')['default']
    DwfFormOptionalContainer: typeof import('./src/components/DwfFormOptionalContainer.vue')['default']
    DwfFormOptionalFieldsContainer: typeof import('./src/components/DwfFormOptionalFieldsContainer.vue')['default']
    DwfFormOptionalItem: typeof import('./src/components/DwfFormOptionalItem.vue')['default']
    DwfFormOptionalObjectContainer: typeof import('./src/components/DwfFormOptionalObjectContainer.vue')['default']
    DwfFormSection: typeof import('./src/components/DwfFormSection.vue')['default']
    DwfPropertiesContainer: typeof import('./src/components/DwfPropertiesContainer.vue')['default']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCardActions: typeof import('vuetify/lib')['VCardActions']
    VCardSubtitle: typeof import('vuetify/lib')['VCardSubtitle']
    VCardText: typeof import('vuetify/lib')['VCardText']
    VCardTitle: typeof import('vuetify/lib')['VCardTitle']
    VChip: typeof import('vuetify/lib')['VChip']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VDialog: typeof import('vuetify/lib')['VDialog']
    VFlex: typeof import('vuetify/lib')['VFlex']
    VForm: typeof import('vuetify/lib')['VForm']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VList: typeof import('vuetify/lib')['VList']
    VListGroup: typeof import('vuetify/lib')['VListGroup']
    VListItem: typeof import('vuetify/lib')['VListItem']
    VListItemTitle: typeof import('vuetify/lib')['VListItemTitle']
    VMenu: typeof import('vuetify/lib')['VMenu']
    VSpacer: typeof import('vuetify/lib')['VSpacer']
  }
}
