export const DIGIWF_ENGINE_SUFFIX = "/clients/digitalwf-backend-service";
export const DATE_FORMAT = "DD.MM.YYYY";
export const FRONTEND_INSTANCE_PATH = "instance";
export const ACCESS_TOKEN_EVENT_NAME_DEFAULT = "access-token-loaded";
export const NEW_TAB_SUFFIX = "(wird in neuem Tab geöffnet)";
export const PAGE_SIZE_DEFAULT = 4;
export const MAX_PAGES_VISIBLE_DEFAULT = 5;
export const ROOT_HEADING_LEVEL_DEFAULT = 1;
export const HTML_HEADING_TAG_MAX_LEVEL = 6;
