spring:
  application:
    name: '@project.artifactId@'
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${SSO_ISSUER_URL}
            user-info-uri: ${SSO_BASE_URL}/realms/${SSO_REALM}/protocol/openid-connect/userinfo
            jwk-set-uri: ${SSO_BASE_URL}/realms/${SSO_REALM}/protocol/openid-connect/certs
            user-name-attribute: user_name
        registration:
          s3:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: ${SSO_S3_CLIENT_ID}
            client-secret: ${SSO_S3_CLIENT_SECRET}
            scope: email, profile, openid  # needed for userInfo endpoint

io:
  muenchendigital:
    digiwf:
      cosys:
        url:
        messageTopic: "dwf-connector-${DIGIWF_ENV}"
        incidentTopic: "dwf-connector-incident-${DIGIWF_ENV}"
        merge:
          datafile: /root/multi
          inputLanguage: Deutsch
          outputLanguage: Deutsch
          keepFields: unresolved-ref

digiwf:
  s3:
    client:
      document-storage-url: '${DIGIWF_S3_HTTPAPI:http://localhost:8086}'
      max-file-size: ${S3_MAX_FILE_SIZE:100MB}
      enable-security: true

management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, prometheus, livenessstate, readinessstate
        path-mapping:
          prometheus: metrics

server:
  shutdown: graceful
