spring.cloud.stream.kafka.binder.brokers=localhost:9092
#spring.cloud.stream.kafka.binder.configuration.security.protocol=SSL
spring.cloud.stream.kafka.binder.consumerProperties.auto.offset.reset=latest
io.muenchendigital.digiwf.cosys.topic=dwf-cosys-local
io.muenchendigital.digiwf.cosys.group=dwf-cosys-local
io.muenchendigital.digiwf.cosys.messageTopic=dwf-connector-message-local
io.muenchendigital.digiwf.cosys.incidentTopic=dwf-connector-incident-local
