spring.cloud.stream.kafka.binder.brokers=localhost:9092
#spring.cloud.stream.kafka.binder.configuration.security.protocol=SSL
spring.cloud.stream.kafka.binder.consumerProperties.auto.offset.reset=latest
io.muenchendigital.digiwf.cosys.topic=dwf-cosys-local
io.muenchendigital.digiwf.cosys.group=dwf-cosys-local
io.muenchendigital.digiwf.cosys.messageTopic=dwf-connector-message-local
io.muenchendigital.digiwf.cosys.incidentTopic=dwf-connector-incident-local
io.muenchendigital.digiwf.cosys.engineTopic=dwf-connector-message-local

logging.level.org.springframework.cloud.function=DEBUG

io.muenchendigital.digiwf.cosys.ssoTokenClientSecret=e2b2b018-abe5-4057-81b9-afdeeab4d8de
io.muenchendigital.digiwf.cosys.url=http://cosysk007.srv.muenchen.de/cosys-eai/rest
io.muenchendigital.digiwf.cosys.ssoTokenClientId=digitalwf
io.muenchendigital.digiwf.cosys.ssoTokenRequestUrl=https://ssotest.muenchen.de/auth/realms/intra/protocol/openid-connect/token

spring.security.oauth2.client.registration.cosys.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.cosys.client-id=digitalwf
spring.security.oauth2.client.registration.cosys.client-secret=e2b2b018-abe5-4057-81b9-afdeeab4d8de
spring.security.oauth2.client.provider.cosys.token-uri=https://ssotest.muenchen.de/auth/realms/intra/protocol/openid-connect/token

