// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DwfDmsInput: typeof import('./src/components/DwfDmsInput.vue')['default']
    DwfObjectPreview: typeof import('./src/components/DwfObjectPreview.vue')['default']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VFadeTransition: typeof import('vuetify/lib')['VFadeTransition']
    VFlex: typeof import('vuetify/lib')['VFlex']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VProgressCircular: typeof import('vuetify/lib')['VProgressCircular']
    VSpacer: typeof import('vuetify/lib')['VSpacer']
    VTextField: typeof import('vuetify/lib')['VTextField']
    VTooltip: typeof import('vuetify/lib')['VTooltip']
  }
}
