### testEventBus with attachements
POST http://localhost:10005/testEventBus
Content-Type: application/json

{
  "receivers": "itm.digiwf@muenchen.de",
  "subject": "Testing Email Integration",
  "body": "This is a test email. You can delete it safely",
  "attachments": [

  ]
}

### testEventBus should fail
POST http://localhost:10005/testEventBus
Content-Type: application/json

{
}
