### testSendMail withoud attachements
POST http://{{host}}/testSendMail
Content-Type: application/json

{
  "receivers": "itm.digiwf@muenchen.de",
  "subject": "Testing Email Integration",
  "body": "This is a test email. You can delete it safely"
}

### testEventBus withoud attachements
POST http://{{host}}/testEventBus
Content-Type: application/json

{
  "receivers": "itm.digiwf@muenchen.de",
  "subject": "Testing Email Integration",
  "body": "This is a test email. You can delete it safely"
}
