name: build apps

on:
  push:
    branches:
      - '**'
    paths:
      - 'digiwf-apps/**'
  pull_request:
    types: [ opened, reopened ]

jobs:
  build:
    uses: ./.github/workflows/workflow-build-apps
    secrets: inherit
