name: Build

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  services:
    uses: ./.github/workflows/workflow-build-services.yaml
    secrets: inherit

  apps:
    uses: ./.github/workflows/workflow-build-apps.yaml
    secrets: inherit
