name: Release Docs

on:
  workflow_call:
    inputs:
      publish:
        description: 'Publish docs?'
        type: boolean
        required: true
        default: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
          cache-dependency-path: "./docs/package-lock.json"
      - run: npm ci
      - run: npm run build
      - name: Upload artifact
        if: inputs.publish == true
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/dist

  deploy-docs:
    if: inputs.publish == true
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build-docs
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
